services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ActuallyAPrettyGoodPassword
      MYSQL_DATABASE: devops-1-docker-laravel
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql-data:
